config/routes.rb
Rails.application.routes.draw do

  root :to => "homes#top"
  devise_for :users

  resources :users, only: [:show, :edit, :update] do
    patch 'withdraw'
  end

  resources :trainings, only: [:index,:new, :show, :edit, :create, :update, :destroy] do
    get 'bookmark'
    get 'ranking'
    resource :favorites, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end

  devise_for :admins

  resources :articles, only: [:index, :new, :show, :edit, :create, :update, :destroy]

  get "search" => "searches#search"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :admin, optional: true
  attachment :article_image

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :training
  
  validates :user_id, uniqueness: { scope: :training_id }
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :training

end

app/models/training.rb
class Training < ApplicationRecord

  belongs_to :user
  attachment :image

  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  has_many :bookmarks, dependent: :destroy

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def self.looks(search, word)
    if search == "partial_match"
      @training = Training.where("title LIKE?","%#{word}%")
    else
      @trainings = Training.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trainings, dependent: :destroy
  attachment :profile_image

  has_many :favorites, dependent: :destroy

  has_many :bookmarks, dependent: :destroy
  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログインした際に遷移先を指定
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      root_path
    when User
      root_path
    end
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # strong parameterで属性(first_nameとlast_name等)をpermitする
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
      [:last_name, :first_name, :last_name_kana, :first_name_kana, :user_name, :email])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :edit]

  def index
    @articles = Article.all
    @articles = Article.page(params[:page]).reverse_order
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :article_image, :description)
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def create
    @training = Training.find(params[:training_id])
    bookmark = @training.bookmarks.new(user_id: current_user.id)
    bookmark.save
    redirect_to trainings_path
  end

  def destroy
    @training = Training.find(params[:training_id])
    bookmark = @training.bookmarks.find_by(user_id: current_user.id)
    bookmark.destroy
    redirect_to trainings_path
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # いいね非同期
  def create
    @training = Training.find(params[:training_id])
    favorite = current_user.favorites.build(training_id: params[:training_id])
    favorite.save
  end

  def destroy
    @training = Training.find(params[:training_id])
    favorite = Favorite.find_by(training_id: params[:training_id], user_id: current_user.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    @trainings = Training.looks(params[:search], params[:word])
    render "/search_result"
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @training = Training.new
  end

  def create
    @training = Training.new(training_params)
    @training.user_id = current_user.id
    @training.save
    redirect_to trainings_path
  end

  def index
    @trainings = Training.all
    @trainings = Training.page(params[:page]).reverse_order
  end

  def show
    @training = Training.find(params[:id])
    @user = current_user
  end

  def edit
    @training = Training.find(params[:id])
  end

  def bookmark
    @bookmarks = Bookmark.where(user_id: current_user.id)
  end

  def ranking
    @rankings = Training.find(Favorite.group(:training_id).order('count(training_id) desc').limit(3).pluck(:training_id))
    @training = Training.all
  end

  def update
    @training = Training.find(params[:id])
    @training.update(training_params)
    redirect_to training_path(@training)
  end

  def destroy
    @training = Training.find(params[:id])
    @training.destroy
    redirect_to trainings_path
  end

  private

  def training_params
    params.require(:training).permit(:title, :image, :set, :time, :description, :genre, :url)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render "edit"
    end
  end

  def withdraw
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :user_name, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<main>
  <h4 class="article-main-title">記事編集</br>（管理者）</h4>
    <div class="edit-area">
      <%= form_with model:@article, local:true do |f| %>

      <%= attachment_image_tag @article, :article_image, class: "article-edit-image" %>
      <!--作成日時を追加-->
      <div class = "created-time">
        <%= @article.created_at.to_s(:datetime_jp) %>
      </div>
      
      <%= f.attachment_field :article_image, class: "change-button" %>

        <table class="article-table">
          <tr class="table-list">
            <th><%= f.label :タイトル %></th>
            <td><%= f.text_field :title, class: "input-area" %></td>
          </tr>

          <tr class="table-list">
              <th><%= f.label :本文 %></th>
              <td><%= f.text_area :description %></td>
          </tr>
        </table>
        <%= f.submit "編集内容を保存", class: "btn btn-info mx-auto d-block" %>
      <% end %>
    </div>
</main>

app/views/articles/index.html.erb
<main>
  <div class = "article">
    <div class = "article-backimage">
      <div class = "article-main-title">ピックアップ</div>
    </div>
  </div>

  <!--adominログアウト-->
  <% if admin_signed_in? %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-link btn-lg btn-block text-white" %>
  <% else %>
  <% end %>

  <div class = "article-container">
    <% @articles.each do |article| %>
      <div class = "article-box">
        <h3 class = "article-title"><%= article.title %></h3>
        <p class = "article-image"><%= attachment_image_tag article, :article_image, class: "article-image"%></p>
        <p class = "article-description"><%= article.description %></p>
        <!--作成日時を追加-->
        <div class = "created-time">
          <%= article.created_at.to_s(:datetime_jp) %>
        </div>
        <!--adominのみ編集・削除可能-->
        <% if admin_signed_in? %>
          <span><%= link_to "編集", edit_article_path(article) %></span>
          <span><%= link_to "削除", article_path(article), method: :delete %></span>
        <% else %>
        <% end %>
      </div>
    <% end %>
  </div>

  <!--ページング機能-->
  <%= paginate @articles, class: "center-block" %>

</main>

app/views/articles/new.html.erb
<main>
  <h4 class="article-main-title">記事新規投稿</br>（管理者）</h4>
    <div class="edit-area">
      <%= form_with model:@article, local:true do |f| %>

      <%= f.attachment_field :article_image, class: "change-button" %>

        <table class="article-table">
          <tr class="table-list">
            <th><%= f.label :タイトル %></th>
            <td><%= f.text_field :title, class: "input-area" %></td>
          </tr>

          <tr class="table-list">
              <th><%= f.label :本文 %></th>
              <td><%= f.text_area :description %></td>
          </tr>
        </table>
        <%= f.submit "投稿する", class: "btn btn-info mx-auto d-block" %>
      <% end %>
    </div>
</main>

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% if training.favorited_by?(current_user) %>
    <span>
      <%= link_to training_favorites_path(training), method: :delete, remote: true do %>
        <i class="fas fa-heart fa-lg favoon"></i><%= training.favorites.count %>
      <% end %>
    </span>
  <% else %>
    <span>
      <%= link_to training_favorites_path(training), method: :post, remote: true do %>
        <i class="far fa-heart fa-lg favooff"></i><%= training.favorites.count%>
      <% end %>
    </span>
  <% end %>
<% else %>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @training.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {training: @training}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @training.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {training: @training}) %>");

app/views/trainings/bookmark.html.erb
<main>
<div class = "trainingbookmark-backimage">
  <div class = "users-title">
    <h2 class = "text-white font-weight-bold">お気に入り</h2>
  </div>
</div>

<div class = "container">
  <div class = "low">
    <div class = "col-10 offset-1 text-center">

      <table class = 'table border '>
          <thead>
            <tr>
              <th></th>
              <th class = "text-white">投稿者</th>
              <th class = "text-white">トレーニング名</th>
            </tr>
          </thead>

          <tbody>
            <% @bookmarks.each do |bookmark| %>
              <tr>
                <td><%= attachment_image_tag bookmark.training.user, :profile_image, size: '30x30', fallback: "no_image.jpg", class: "rounded-circle"%></td>
                <td class = "text-white"><%= bookmark.training.user.user_name %></td>
                <td>
                  <%= link_to training_path(bookmark.training) do %>
                    <%= bookmark.training.title %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/trainings/edit.html.erb
<main>
  <div class = "edit-backimage">
    <div class = "users-title">
      <h2 class = "text-white">投稿編集</h2>
    </div>
  </div>


  <div class = "container">
    <div class = "low">
      <div class = "col-10 offset-1 mx-auto text-center text-white">
        <%= form_with model:@training, local:true do |f| %>

        <%= attachment_image_tag @training, :image, class: "trainingimg" %>
        <%= f.attachment_field :image, placeholder: "投稿画像", class: "text-white m-3" %>

        <table class = 'table inin'>
          <tr>
            <td class="text-white font-weight-bold">トレーニング名</td>
            <td>
              <%= f.text_field :title, class: "border border-dark rounded text-dark", :size => "50" %>
            </td>
          </tr>
          <tr>
            <td class="text-white">時間or回数 × セット</td>
            <td>
              <%= f.text_field :time, :size => "24*30", class: "border border-dark rounded text-dark" %>×
              <%= f.text_field :set, :size => "24*30", class: "border border-dark rounded text-dark" %>
            </td>
          </tr>
          <tr>
            <td class="text-white">ジャンル</td>
            <td><%= f.select :genre, [["腕", "腕"], ["胸", "胸"],["腹", "腹"],["足", "足"]], include_blank: "選択して下さい" %></td>
          </tr>
          <td class="text-white font-weight-bold">参照URL名</td>
            <td><%= f.text_field :url, class: "border border-dark rounded text-dark", :size => "50" %></td>
          <tr>
            <td class="text-white">説明</td>
            <td><%= f.text_area :description, size: "50x5",class: "border border-dark rounded text-dark" %>
          </tr>
        </table>
        <%= f.submit '編集内容を保存', class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/trainings/index.html.erb
<div class = "trainingindex-backimage">
  <div class = "users-title">
    <h2 class = "text-white font-weight-bold">トレーニング一覧</h2>
  </div>
</div>

<div class = "index-container">
  <% @trainings.each do |training| %>
    <div class = "index-box">
      <div class = "post">

          <!--トレーニング投稿情報-->
        <p><%= attachment_image_tag training, :image, size:'250x200',class: "id-image" %></p>
        <p class = "text-center">
          <%= attachment_image_tag training.user, :profile_image, size:'33x33', fallback: "no_image.jpg", class: "rounded-circle" %>
          <%= training.user.user_name %>
        </p>
        <p class = "break text-center">【<%= link_to training.title, training_path(training.id) %>】</p>
        <p class = "text-center"><%= training.time %>×<%= training.set %></p>
        <p class = "break text-center" ><%= training.description %></p>

        <!--ボーダー線-->
        <hr width="100%"></hr>

        <div class="content">
          <!--いいね機能-->
          <div id="favorites_buttons_<%= training.id %>">
             <%= render partial: 'favorites/favorite', locals: { training: training} %>
          </div>
          <!--ブックマーク機能-->
          <% if user_signed_in? %>
            <% if training.bookmarked_by?(current_user) %>
                <span><%= link_to "", training_bookmarks_path(training), method: :delete, class: "fas fa-bookmark fa-lg" %></span>
              <% else %>
                <span><%= link_to "", training_bookmarks_path(training), method: :post, class: "far fa-bookmark fa-lg" %></></span>
            <% end %>
          <% else %>
          <% end %>
          <!--編集削除機能-->
          <% if training.user == current_user %>
            <span>
              <%= link_to "編集", edit_training_path(training) %>
            </span>
            <span>
              <%= link_to "削除", training_path(training), method: :delete %>
            </span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= paginate @trainings, class: "center-block" %>

app/views/trainings/new.html.erb
<div class = "trainingnew-backimage">
  <div class = "trainings-title">
    <h2 class = "text-white font-weight-bold">新規投稿</h2>
  </div>
</div>

<div class = "container">
  <div class = "low">
    <div class = "col-10 offset-1 mx-auto text-center bg-white">

    <%= form_with model: @training, local:true do |f| %>

    <table class = 'table inin'>
      <tr>
        <td class="text-dark">トレーニング名</td>
        <td><%= f.text_field :title, size: "50", class: "text-dark" %></td>
      </tr>
      <tr>
        <td class="text-dark">時間or回数 × セット</td>
        <td><%= f.text_field :time, :size => "24", class: "text-dark" %>×<%= f.text_field :set, :size => "24", class: "text-dark" %></td>
      </tr>
      <!--ジャンル　プルダウン選択式-->
      <tr>
        <td class="text-dark">ジャンル</td>
        <td><%= f.select :genre, [["腕", "腕"], ["胸", "胸"],["腹", "腹"],["背中", "背中"],["脚", "脚"]], include_blank: "選択して下さい", size: "50x5",class: "text-dark" %></td>
      </tr>
      <tr>
        <td class="text-dark">トレーニング詳細</td>
        <td><%= f.text_area :description, size: "50x5",class: "border border-dark rounded text-dark" %></td>
      </tr>
      <tr>
        <td class="text-dark">トレーニング画像</td>
        <td><%= f.attachment_field :image %></td>
      </tr>
      <tr>
        <td class="text-dark">参照URL</td>
        <td><%= f.text_field :url, size: "50", class: "text-dark" %></td>
      </tr>
    </table>

    <div class="row">
      <div class="col-10 offset-1 ">
        <%= f.submit '投稿', class: "btn btn-primary btn-sm mx-auto d-block m-2 text-white" %>
      </div>
    </div>
    <% end %>

    </div>
  </div>
</div>

app/views/trainings/ranking.html.erb
<main>
  <div class = "trainingranking-backimage">
    <div class = "users-title">
      <h2 class = "text-white font-weight-bold">ランキング</h2>
    </div>
  </div>

  <div class = "index-container">
    <% @rankings.each do |training| %>
      <div class = "index-box">
        <div class = "post">
          <p><%= attachment_image_tag training, :image, size:'250x200',class: "id-image" %></p>
          <p class = "text-center">
            <%= attachment_image_tag training.user, :profile_image, size:'33x33', fallback: "no_image.jpg", class: "rounded-circle" %>
            <%= training.user.user_name %>
          </p>
          <p class = "break text-center">【<%= link_to training.title, training_path(training.id) %>】：<%= training.genre %></p>
          <p class = "text-center"><%= training.time %>×<%= training.set %></p>
          <p class = "break text-center" ><%= training.description %></p>

          <!--ボーダー線-->
          <hr width="100%"></hr>

          <div class="content">

          <!--いいね機能-->
          <div id="favorites_buttons_<%= training.id %>">
             <%= render partial: 'favorites/favorite', locals: { training: training} %>
          </div>

          <!--ブックマーク機能-->
          <% if user_signed_in? %>
            <% if training.bookmarked_by?(current_user) %>
                <span><%= link_to "", training_bookmarks_path(training), method: :delete, class: "fas fa-bookmark fa-lg" %></span>
              <% else %>
                <span><%= link_to "", training_bookmarks_path(training), method: :post, class: "far fa-bookmark fa-lg" %></></span>
            <% end %>
          <% else %>
          <% end %>

        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/trainings/show.html.erb
<div class = "trainingshow-backimage">
  <div class = "users-title">
    <h2 class = "text-white font-weight-bold">トレーニング詳細</h2>
  </div>
</div>

<div class = "container">
  <div class = "low">
    <div class="col-md-10 offset-1 text-center showbody">
      <h3 class = "text-center"><b><%= @training.title %></b></h3>
      <%= attachment_image_tag @training, :image, class:"trainingimg" %>

      <table class = 'table border'>
        <tr>
          <td class = 'thshow border bg-light'>投稿者</td>
          <td class = "text-dark"><%= @training.user.user_name %></td>
        </tr>
        <tr>
          <td class = 'information border bg-light'>時間or回数 × セット</td>
          <td class = "text-dark"><%= @training.time %>×<%= @training.set %></td>
        </tr>
        <tr>
          <td class = 'information border bg-light'>ジャンル</td>
          <td class = "text-dark"><%= @training.genre %></td>
        </tr>
        <tr>
          <td class = 'information border bg-light'>参照URL</td>
          <!--Rinku gem追加 URLを飛べるように表示　-->
          <td class = "text-dark"><%= Rinku.auto_link(@training.url, :all, 'target="_blank"').html_safe %></td>
        </tr>
        <tr>
          <td class = 'information border bg-light'>詳細</td>
          <!--段落表示(split("\n"),tag(:br))-->
          <td class = "text-dark text-left"><%=safe_join(@training.description.split("\n"),tag(:br))%></td>
        </tr>
      </table>

      <div class="text-right">
          <!--いいね機能-->
          <span id="favorites_buttons_<%= @training.id %>">
             <%= render partial: 'favorites/favorite', locals: { training: @training} %>
          </span>

          <!--ブックマーク機能-->
          <% if user_signed_in? %>
            <% if @training.bookmarked_by?(current_user) %>
                <span><%= link_to "", training_bookmarks_path(@training), method: :delete, class: "fas fa-bookmark fa-lg" %></span>
              <% else %>
                <span><%= link_to "", training_bookmarks_path(@training), method: :post, class: "far fa-bookmark fa-lg" %></></span>
            <% end %>
          <% else %>
          <% end %>

          <% if @training.user == current_user %>
            <span>
              <%= link_to "編集", edit_training_path(@training) %>
            </span>
            <span>
              <%= link_to "削除", training_path(@training), method: :delete %>
            </span>
          <% end %>
      </div>

      <div class = "text-right"><%= @training.updated_at %></div>
    </div>
  </div>
</div>