config/routes.rb
Rails.application.routes.draw do

  root :to => "homes#top"
  devise_for :users

  resources :users, only: [:show, :edit, :update] do
    patch 'withdraw'
  end

  resources :trainings, only: [:index,:new, :show, :edit, :create, :update, :destroy] do
    get 'bookmark'
    get 'ranking'
    resource :favorites, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end

  devise_for :admins

  resources :articles, only: [:index, :new, :show, :edit, :create, :update, :destroy]

  get "search" => "searches#search"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trainings, dependent: :destroy
  attachment :profile_image

  has_many :favorites, dependent: :destroy

  has_many :bookmarks, dependent: :destroy
  
  

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  # 退会後のログインを
  def reject_inactive_user
    @user = User.find_by(name: params[:user][:name])
    if @user
      if @user.valid_password?(params[:user][:password]) && !@user.is_valid
        redirect_to new_user_session_path
      end
    end
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render "edit"
    end
  end

  def withdraw
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :user_name, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class = "edit-backimage">
  <div class = "users-title">
    <h2 class = "text-white font-weight-bold">アカウント編集</h2>
  </div>
</div>

<div class = "container">
  <div class = "low">
    <div class = "col-10 offset-1 mx-auto text-center text-white">
        <%= form_with model:@user, local:true do |f| %>
          <table class = 'table inin'>
            <tr>
              <td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "rounded-circle" %></td>
              <td><%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: " text-white" %></td>
            </tr>
            <tr>
              <td class="text-white">氏名</td>
              <td>
                <%= f.text_field :last_name, :size => "20*30", class: "border border-dark rounded text-dark" %>
                <%= f.text_field :first_name, :size => "20*30", class: "border border-dark rounded text-dark" %>
              </td>
            </tr>
            <tr>
              <td class="text-white">カナ</td>
              <td>
                <%= f.text_field :last_name_kana, :size => "20*30", class: "border border-dark rounded text-dark" %>
                <%= f.text_field :first_name_kana, :size => "20*30", class: "border border-dark rounded text-dark" %>
              </td>
            </tr>
            <tr>
              <td class="text-white">ユーザー名</td>
              <td><%= f.text_field :user_name, class: "border border-dark rounded text-dark",:size => "42" %></td>
            </tr>
            <tr>
              <td class="text-white">メールアドレス</td>
              <td><%= f.text_field :email, class: "border border-dark rounded text-dark",:size => "42" %></td>
            </tr>
          </table>
          <%= f.submit '編集内容を保存', class: 'btn btn-link mx-auto d-block m-2 btn-outline-success text-white' %>
          <% end %>
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<main>
  <div class = "user">
    <div class = "mypage-backimage">
      <div class = "user-main-title">マイページ</div>
    </div>
  </div>
  <div class = "user-container">
    <div class = "user-box">
      <div class = "profile-image">
          <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", class: "profile-image"%>
      </div>
      <table class = 'border user-table-list'>
        <!-- log in user情報-->
        <tr>
          <th class = 'bg-light'>氏名</th>
          <td class = "text-white"><%= @user.last_name %><%= @user.first_name %></td>
        </tr>
        <tr>
          <th class = 'bg-light'>カナ</th>
          <td class = "text-white"><%= @user.last_name_kana %><%= @user.first_name_kana %></td>
        </tr>
        <tr>
          <th class = 'bg-light'>ユーザー名</th>
          <td class = "text-white"><%= @user.user_name %></td>
        </tr>
        <tr>
          <th class = 'bg-light'>メールアドレス</th>
          <td class = "text-white"><%= @user.email %></td>
        </tr>
      </table>
      <div class = "btn-area">
        <%= link_to '編集する', edit_user_path, class: "btn btn-link btn-outline-success text-white m-3"%>
        <%= link_to '退会する', user_withdraw_path(current_user), method: :patch, "data-confirm" => "本当に退会しますか？", class: "btn btn-link btn-outline-danger text-white m-3" %>
      </div>
    </div>
  </div>
</main>




<!--<main>-->
<!--  <div class = "user">-->
<!--    <div class = "mypage-backimage">-->
<!--      <div class = "user-main-title">マイページ</div>-->
<!--    </div>-->
<!--  </div>-->

<!--  <div class = "user-container">-->
<!--    <div class = "user-box">-->
<!--      <div class = "profile-image">-->
<!--        <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", class: "profile-image"%>-->
<!--      </div>-->

      <!--user情報-->
<!--      <table class = "user-table">-->
<!--          <tr class = "user-table-list">-->
<!--            <th>氏名</th>-->
<!--            <td><%= @user.last_name %><%= @user.first_name %></td>-->
<!--          </tr>-->
<!--          <tr class = "user-table-list">-->
<!--            <th>カナ</th>-->
<!--            <td><%= @user.last_name_kana %><%= @user.first_name_kana %></td>-->
<!--          </tr>-->
<!--          <tr class = "user-table-list">-->
<!--            <th>ユーザー名</th>-->
<!--            <td><%= @user.user_name %></td>-->
<!--          </tr>-->
<!--          <tr class = "user-table-list">-->
<!--            <th>メールアドレス</th>-->
<!--            <td><%= @user.email %></td>-->
<!--          </tr>-->
<!--      </table>-->

<!--      <%= link_to '編集する', edit_user_path, class: "btn btn-link btn-outline-success"%>-->
<!--      <%= link_to '退会する', user_withdraw_path(current_user), method: :patch,
       "data-confirm" => "本当に退会しますか？", class: "btn btn-link btn-outline-danger" %>-->

<!--    </div>-->
<!--  </div>-->
<!--</main>-->