config/routes.rb
Rails.application.routes.draw do

  root :to => "homes#top"
  devise_for :users

  resources :users, only: [:show, :edit, :update] do
    patch 'withdraw'
  end

  resources :trainings, only: [:index,:new, :show, :edit, :create, :update, :destroy] do
    get 'bookmark'
    get 'ranking'
    resource :favorites, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end

  devise_for :admins

  resources :articles, only: [:index, :new, :show, :edit, :create, :update, :destroy]

  get "search" => "searches#search"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :admin, optional: true
  attachment :article_image

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :training
  
  validates :user_id, uniqueness: { scope: :training_id }
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :training

end

app/models/training.rb
class Training < ApplicationRecord

  belongs_to :user
  attachment :image

  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  has_many :bookmarks, dependent: :destroy

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def self.looks(search, word)
    if search == "partial_match"
      @training = Training.where("title LIKE?","%#{word}%")
    else
      @trainings = Training.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trainings, dependent: :destroy
  attachment :profile_image

  has_many :favorites, dependent: :destroy

  has_many :bookmarks, dependent: :destroy
  
  

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :edit]

  def index
    @articles = Article.all
    @articles = Article.page(params[:page]).reverse_order
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :article_image, :description)
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def create
    @training = Training.find(params[:training_id])
    bookmark = @training.bookmarks.new(user_id: current_user.id)
    bookmark.save
    redirect_to trainings_path
  end

  def destroy
    @training = Training.find(params[:training_id])
    bookmark = @training.bookmarks.find_by(user_id: current_user.id)
    bookmark.destroy
    redirect_to trainings_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    @trainings = Training.looks(params[:search], params[:word])
    render "/search_result"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render "edit"
    end
  end

  def withdraw
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :user_name, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center"><%= link_to '©KINTORE︎', destroy_admin_session_path, method: :delete, class: "text-white" %></div>
</footer>

app/views/layouts/_user_header.html.erb
<header>
  <div class="navbar">
    <!--サイト名-->
    <a class="title" href="/"><h3 class="text-white">KINTORE</h3></a>
      <!--ハンバーガーメニュー-->
      <div id="sp-menu">
        <ul>
          <li></li>
          <li></li>
          <li><a><%= render'/search' %></a></li>
            <% if user_signed_in? %>
                    <li><%= link_to 'ホーム', root_path, class: "text-white" %></li>
                    <li><%= link_to 'マイページ', user_path(current_user), class: "text-white" %></li>
                    <li><%= link_to '新規投稿', new_training_path, class: "text-white" %></li>
                    <li><%= link_to 'お気に入り', training_bookmark_path(current_user), class: "text-white" %></li>
                    <li><%= link_to 'ランキング', training_ranking_path(current_user), class: "text-white" %></li>
                    <li><%= link_to '投稿一覧', trainings_path, class: "text-white" %></li>
                    <li><%= link_to '特集', articles_path, class: "text-white" %></li>
                    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "text-white" %></li>
                <% else %>
                    <li><%= link_to 'ホーム', root_path, class: "text-white" %></li>
                    <li><%= link_to '新規登録', new_user_registration_path, class: "text-white" %></li>
                    <li><%= link_to '投稿一覧', trainings_path, class: "text-white" %></li>
                    <%#= link_to 'ランキング', training_ranking_path, class: "btn btn-link btn-lg btn-block text-white" %>
                    <li><%= link_to '特集', articles_path, class: "text-white" %></li>
                    <li><%= link_to 'ログイン', new_user_session_path, class: "text-white" %></li>
            <% end %>
        </ul>
      </div>

      <div id="hm-icon">
        <a class="menu-trigger" href="#">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>

      <script src="js/jquery.min.js"></script>
      <script src="js/script.js"></script>

    <!--</li>-->

  </div>
</header>

app/views/layouts/_user_sidebar.html.erb
<div class = "sidebar">
    <!--<div class ="sidebar_fixed">-->
        <nav class="navbar-dark text-center h-100">
                <% if user_signed_in? %>
                    <li><%= link_to 'ホーム', root_path, class: "btn btn-link btn-lg btn-block btn-outline-link border-0 text-white" %></li>
                    <li><%= link_to 'マイページ', user_path(current_user), class: "btn btn-link btn-lg btn-block text-white" %></li>
                    <li><%= link_to '新規投稿', new_training_path, class: "btn btn-link btn-lg btn-block text-white" %></li>
                    <li><%= link_to 'お気に入り', training_bookmark_path(current_user), class: "btn btn-link btn-lg btn-block text-white" %></li>
                    <li><%= link_to 'ランキング', training_ranking_path(current_user), class: "btn btn-link btn-lg btn-block text-white" %></li>
                    <li><%= link_to '投稿一覧', trainings_path, class: "btn btn-link btn-lg btn-block text-white" %></li>
                    <li><%= link_to '特集', articles_path, class: "tbtn btn-link btn-lg btn-block text-white" %></li>
                    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-link btn-lg btn-block text-white" %></li>
                <% else %>
                    <li><%= link_to 'ホーム', root_path, class: "btn btn-link btn-lg btn-block text-white" %></li>
                    <li><%= link_to '新規登録', new_user_registration_path, class: "btn btn-link btn-lg btn-block text-white" %></li>
                    <li><%= link_to '投稿一覧', trainings_path, class: "btn btn-link btn-lg btn-block text-white" %></li>
                    <li><%#= link_to 'ランキング', training_ranking_path, class: "btn btn-link btn-lg btn-block text-white" %></li>
                    <li><%= link_to '特集', articles_path, class: "btn btn-link btn-lg btn-block text-white" %></li>
                    <li><%= link_to 'ログイン', new_user_session_path, class: "btn btn-link btn-lg btn-block text-white" %></li>
                <% end %>
        </nav>
    <!--</div>-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KINTORE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- FontAwesomeの読み込み -->
    <script src="https://kit.fontawesome.com/ca1289ead1.js" crossorigin="anonymous"></script>
    <!--ハンバーガーメニュー-->
    <link rel="stylesheet" href="css/style.css" />
    <!--各デバイスで表示される領域-->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <!--レスポンシブ対応-->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>

  <body>
    <%= render'layouts/user_header' %>
    <%= yield %>
    <%= render'layouts/footer' %>
  </body>

</html>